---
title: "Data Import"
output: github_document
---

```{r echo=FALSE}
library(tidyverse)
```

## Data Import CSVs

Let's import data using the "readr" package.

```{r}
litters_df<-read_csv("data/FAS_litters.csv")
## inside the janitor package use the clean_name function only
## that will help you from loading too much packages, or too many package with same function
litters_df<-janitor::clean_names(litters_df)
```

Look at the data
```{r}
litters_df
head(litters_df)
tail(litters_df)
```

```{r,eval=FALSE}
view(litters_df)

```


```{r}
skimr::skim(litters_df)
```

`read_csv` options ..
```{r eval=FALSE}

read_csv("data/FAS_litters.csv",na=c("","NA",999,88),skip=2)


```
##  Other file formats

We need to read in an excel spreadsheet 
```{r}
library(readxl)
mlb_df<-read_excel("data/mlb11.xlsx")
```
```{r eval=FALSE}
View(mlb_df)
```
```{r}
  lotr_words_df=read_excel("data/LotR_Words.xlsx",range="B3:D6")
```
we need to read SAS dataset 
```{r}
library(haven)
pulse_df=read_sas("data/public_pulse_data.sas7bdat")

```
 ## data export
 
```{r}
 
 write_csv(lotr_words_df,file="data/lotr_words_df.csv")
```



